apiVersion: apps/v1
kind: Deployment
metadata:
  name: mushrooms-website-deployment
  namespace: nft-dev
  labels:
    app: mushrooms-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mushrooms-website
  template:
    metadata:
      labels:
        app: mushrooms-website
    spec:
      containers:
        - name: mushrooms-website
          image: 766525882049.dkr.ecr.us-east-2.amazonaws.com/mushrooms-website
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: mushrooms-website-service
  namespace: nft-dev
spec:
  selector:
    app: mushrooms-website
  ports:
    - port: 5678 # Default port for image
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: mushrooms-website-ingress
  namespace: nft-dev
spec:
  rules:
    - host: dev.madmartysmushrooms.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mushrooms-website-service
                port:
                  number: 5678
